"""The daily document — a model, not a dictionary.

Two consumers see this shape and must see the same one: the vendor adapter
that ships it, and the preview that shows an administrator exactly what will
leave today (REQ-009 R7). Neither may add a field of its own, which is what
`extra="forbid"` and `frozen=True` say here; the preview is only honest if it
renders the same object the sender sends.

The types are the other half of the R4 contract, and the stricter half. Every
number is a `StrictInt` and every flag a `StrictBool`, so a string cannot
coerce its way into a field meant to count something — not `"12"`, not
anything else. Every string in the document has an answer for where it came
from, and none of the answers is "the customer's configuration, verbatim":

- `install_id` — generated by the installation from nothing (`install.py`);
- `version`/`commit` — written by our own build (`util/build_info.py`);
- `llm_provider`/`llm_model`/`admin_language` — through `normalize.py`.

`day` is a UTC date, like everything the counters and the run journal record.
The installation's own offset from UTC travels as its own field instead — a
number, and one that cannot name a city.
"""

from datetime import date

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, field_validator

from itop_ai_assistant.state.counters import Counter

_STRICT = ConfigDict(frozen=True, extra="forbid")


class Build(BaseModel):
    """Which build of ours is running, and on what.

    Named apart from `util/build_info.py::BuildInfo`, which is where these two
    values come from: that one is what the artifact says about itself, this
    one is the group of the document that carries it.
    """

    model_config = _STRICT

    version: str
    # `None` for a checkout that was never built — `util/build_info.py`
    commit: str | None
    # Major and minor only — see `normalize.python_version`
    python_version: str
    containerized: StrictBool


class Environment(BaseModel):
    """What the installation has around it.

    Redis is deliberately not a field. The document is assembled out of Redis
    — the counters and the install id both live there — so the field could
    never hold `false`, and a constant dressed as an observation is worse than
    no observation. Qdrant is a field because it genuinely is optional, and
    `vector_available` says the harder thing next to it: not "the store is
    deployed" but "the layer answers".

    Country and region are absent on purpose and not by omission: the receiver
    derives the country from the connection address (ADR-031), and we have
    nothing to compute it from except the customer's own configuration — that
    is, from exactly what we must not touch.
    """

    model_config = _STRICT

    qdrant: StrictBool
    vector_available: StrictBool
    # `None` for an installation nobody has opened the admin UI on. Not a
    # default we invented — R10 asks for the signal that already exists.
    admin_language: str | None
    utc_offset_minutes: StrictInt


class Configuration(BaseModel):
    """How the installation is set up, in terms that cannot carry prose.

    `settings` is a map rather than a list of named fields because the fields
    belong to the modules, not here: `builder.py` takes every `bool` and `int`
    a module's own config section declares, under `<section>_<field>`. A new
    module describes itself without a line changed in this file, and a module's
    OQL, class list or note template cannot appear here at all — not because
    they were left out, but because they are neither a `bool` nor an `int`.
    """

    model_config = _STRICT

    dry_run: StrictBool
    # From the provider registry, or `other` — `normalize.llm_provider`
    llm_provider: str | None
    # Shape-checked, not enumerated — `normalize.model_name`
    llm_model: str | None
    settings: dict[str, StrictBool | StrictInt]


class TelemetryDocument(BaseModel):
    """One installation, one UTC day, one document."""

    model_config = _STRICT

    install_id: str
    day: date
    build: Build
    environment: Environment
    configuration: Configuration
    # Keyed by `Counter`, every counter present including the zeros: the shape
    # of the document must not depend on what happened to be incremented.
    activity: dict[str, StrictInt]

    @field_validator("activity")
    @classmethod
    def check_every_counter_and_nothing_else(cls, value: dict[str, int]) -> dict[str, int]:
        """The activity group is `state/counters.py`'s enumeration, exactly.

        Checked rather than trusted: this is the one group assembled from a
        name-keyed source, and the difference between "a counter is missing"
        and "a key appeared that is not a counter" is worth failing over
        before the document leaves.
        """
        expected = {counter.value for counter in Counter}
        if value.keys() != expected:
            missing = sorted(expected - value.keys())
            unknown = sorted(value.keys() - expected)
            raise ValueError(f"activity must hold every counter and only counters; missing {missing}, extra {unknown}")
        return value
