"""The one rule the whole requirement rests on: what does not check out is `other`.

REQ-009 R4 is a contract about what we never collect — ticket text, names,
URLs, keys, iTop object ids — and a contract like that does not hold by good
intentions at the call sites. It holds because a value that is not recognized
is replaced here, before it can reach the document, and because the document's
other half (`builder.py`) admits only integers and booleans, which cannot carry
prose at all.

Two string values reach the document through this module, and they are guarded
differently on purpose:

- the LLM provider is a real enumeration — `core/llm_providers.py` already
  lists every endpoint this build can talk to, so an unknown value is a value
  we did not ship;
- the model name is not an enumeration and cannot become one without a
  curated list of families that would exist for telemetry and nothing else,
  and would need an entry for every model released anywhere. What guards it
  instead is its *shape*: a lowercase model identifier is letters, digits and
  a handful of separators, and nothing else gets through. `qwen3-32b` and
  `gpt-4o` travel as themselves; a space, a Cyrillic letter or anything longer
  than a model id becomes `other`.

  The residual risk is named rather than hidden: an ASCII suffix somebody
  typed into their own configuration passes the shape check. R4 holds here by
  form, not by enumeration, and that is a smaller guarantee than the one the
  provider field gets.

Nothing else in the document is a string a customer can influence: the build
version and commit are generated by our own build, and the language is already
normalized by `settings/module_locales.py` before it is stored.
"""

import re
import sys
from datetime import datetime
from pathlib import Path

from itop_ai_assistant.core.llm_providers import PROVIDERS

#: What replaces anything unrecognized. One constant, so that a reader
#: grepping for it finds every field that can degrade.
OTHER = "other"

#: A model identifier as every registry writes one: `qwen3-32b`,
#: `gpt-4o-mini`, `Qwen/Qwen3-32B`, `deepseek-chat`, `llama3.2:3b`. The bound
#: is part of the guard, not politeness — a long value is prose, not an id.
_MODEL_NAME = re.compile(r"^[a-z0-9._:/-]{1,64}$")

#: A scheme or a bare `//` means somebody put an endpoint address where the
#: model goes, and R4 names addresses explicitly. Cheap to catch, so caught —
#: unlike the two cases named below it.
_LOOKS_LIKE_A_URL = "//"

#: Files a container runtime leaves in the filesystem root. Docker writes the
#: first, Podman the second; neither is present on a bare host.
_CONTAINER_MARKERS = (Path("/.dockerenv"), Path("/run/.containerenv"))


def llm_provider(value: str | None) -> str | None:
    """The provider id if this build ships one by that name, else `other`.

    `None` for an installation that has not been configured yet — "not set"
    and "set to something we do not know" are different answers, and
    collapsing them would hide a fresh install among the misconfigured ones.
    """
    if not value:
        return None
    return value if value in PROVIDERS else OTHER


def model_name(value: str | None) -> str | None:
    """The model name lowercased if it has the shape of one, else `other`.

    What the shape catches is the case R4 gives its own example for: a name
    with a comment appended to it, in any alphabet — spaces, Cyrillic,
    punctuation and anything longer than an identifier all fail.

    What it cannot catch is worth naming here rather than discovering later:
    an opaque ASCII token and a bare `host:port` are built from the same
    characters a model id is, and no rule short of a curated list of model
    families tells them apart. Both mean somebody typed into the model field
    something that is not a model — an installation in which nothing works —
    but the shape check will pass them.
    """
    if not value:
        return None
    lowered = value.strip().lower()
    if _LOOKS_LIKE_A_URL in lowered:
        return OTHER
    return lowered if _MODEL_NAME.match(lowered) else OTHER


def python_version() -> str:
    """`"3.13"` — the interpreter's major and minor, and no patch level.

    The patch level answers no question the requirement asks and would split
    every installation into a series of near-identical ones.
    """
    return f"{sys.version_info.major}.{sys.version_info.minor}"


def utc_offset_minutes() -> int:
    """This host's offset from UTC, in minutes, right now.

    Minutes rather than hours: not every offset is a whole hour. Read at build
    time rather than cached — a document built after a DST change should say
    what is true then.
    """
    offset = datetime.now().astimezone().utcoffset()
    return 0 if offset is None else int(offset.total_seconds() // 60)


def in_container() -> bool:
    """Whether this process runs in a container, as far as the filesystem says."""
    return any(marker.exists() for marker in _CONTAINER_MARKERS)
