name: itop-ai-assistant
services:
  itop:
    image: vbkunin/itop
    ports:
      - "8000:80"
    volumes:
      - itop-db:/var/lib/mysql
    environment:
      MYSQL_PASS: 123456

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  assistant:
    build:
      context: ../assistant
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - redis
#    env_file:
#      - .env

volumes:
  itop-db:
  redis-data:
